version: "2.1"
services:
  rabbitmq:
    image: 'drivehub.azurecr.io/meateam/rabbitmq:latest'
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://rabbitmq:15672" ]
      interval: 10s
      timeout: 10s
      retries: 15

  # rabbitmq:
  #   image: "rabbitmq:3-management"
  #   hostname: "rabbitmq"
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   labels:
  #     NAME: "rabbitmq"
  #   volumes:
  #     - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  managerService:
    image: manager-spring-boot
    build: ./manager-service
    environment:
      - INDEXING_MANAGER_SERVICE_HC_PORT=${INDEXING_MANAGER_SERVICE_HC_PORT}
      - INDEXING_RABBIT_URL=${INDEXING_RABBIT_URL}
      - INDEXING_EXCHANGE_NAME=${INDEXING_EXCHANGE_NAME}
      - INDEXING_EVENTS_QUEUE_NAME=${INDEXING_EVENTS_QUEUE_NAME}
      - INDEXING_EVENTS_ROUTING_KEY=${INDEXING_EVENTS_ROUTING_KEY}
      - INDEXING_DELETE_QUEUE_NAME=${INDEXING_DELETE_QUEUE_NAME}
      - INDEXING_DELETE_ROUTING_KEY=${INDEXING_DELETE_ROUTING_KEY}
      - INDEXING_DRIVE_SERVICE_QUEUE_NAME=${INDEXING_DRIVE_SERVICE_QUEUE_NAME}
      - INDEXING_DRIVE_SERVICE_ROUTING_KEY=${INDEXING_DRIVE_SERVICE_ROUTING_KEY}
      - INDEXING_ERROR_QUEUE_NAME=${INDEXING_ERROR_QUEUE_NAME}
      - INDEXING_ERROR_ROUTING_KEY=${INDEXING_ERROR_ROUTING_KEY}
    depends_on:
        - rabbitmq

  driveService:
    image: drive-spring-boot
    build: ./drive-service
    environment:
      - INDEXING_DRIVE_SERVICE_HC_PORT=${INDEXING_DRIVE_SERVICE_HC_PORT}
      - INDEXING_RABBIT_URL=${INDEXING_RABBIT_URL}
      - INDEXING_EXCHANGE_NAME=${INDEXING_EXCHANGE_NAME}
      - INDEXING_EVENTS_QUEUE_NAME=${INDEXING_EVENTS_QUEUE_NAME}
      - INDEXING_EVENTS_ROUTING_KEY=${INDEXING_EVENTS_ROUTING_KEY}
      - INDEXING_DELETE_QUEUE_NAME=${INDEXING_DELETE_QUEUE_NAME}
      - INDEXING_DELETE_ROUTING_KEY=${INDEXING_DELETE_ROUTING_KEY}
      - INDEXING_DRIVE_SERVICE_QUEUE_NAME=${INDEXING_DRIVE_SERVICE_QUEUE_NAME}
      - INDEXING_DRIVE_SERVICE_ROUTING_KEY=${INDEXING_DRIVE_SERVICE_ROUTING_KEY}
      - INDEXING_ERROR_QUEUE_NAME=${INDEXING_ERROR_QUEUE_NAME}
      - INDEXING_ERROR_ROUTING_KEY=${INDEXING_ERROR_ROUTING_KEY}
      - INDEXING_PARSING_SERVICE_QUEUE_NAME=${INDEXING_PARSING_SERVICE_QUEUE_NAME}
      - INDEXING_PARSING_SERVICE_ROUTING_KEY=${INDEXING_PARSING_SERVICE_ROUTING_KEY}
      - INDEXING_ELASTIC_SERVICE_QUEUE_NAME=${INDEXING_ELASTIC_SERVICE_QUEUE_NAME}
      - INDEXING_ELASTIC_SERVICE_ROUTING_KEY=${INDEXING_ELASTIC_SERVICE_ROUTING_KEY}
      - INDEXING_FOLDER_TYPE=${INDEXING_FOLDER_TYPE}
      - INDEXING_FILE_SERVICE_URL=${INDEXING_FILE_SERVICE_URL}
      - INDEXING_PERMISSION_SERVICE_URL=${INDEXING_PERMISSION_SERVICE_URL}
      - INDEXING_USER_SERVICE_URL=${INDEXING_USER_SERVICE_URL}
      - INDEXING_DOWNLOAD_SERVICE_URL=${INDEXING_DOWNLOAD_SERVICE_URL}
    depends_on:
      - rabbitmq

  deleteService:
    image: delete-spring-boot
    build: ./delete-service
    environment:
      - INDEXING_DELETE_SERVICE_HC_PORT=${INDEXING_DELETE_SERVICE_HC_PORT}
      - INDEXING_RABBIT_URL=${INDEXING_RABBIT_URL}
      - INDEXING_EXCHANGE_NAME=${INDEXING_EXCHANGE_NAME}
      - INDEXING_EVENTS_QUEUE_NAME=${INDEXING_EVENTS_QUEUE_NAME}
      - INDEXING_EVENTS_ROUTING_KEY=${INDEXING_EVENTS_ROUTING_KEY}
      - INDEXING_DELETE_QUEUE_NAME=${INDEXING_DELETE_QUEUE_NAME}
      - INDEXING_DELETE_ROUTING_KEY=${INDEXING_DELETE_ROUTING_KEY}
      - INDEXING_DRIVE_SERVICE_QUEUE_NAME=${INDEXING_DRIVE_SERVICE_QUEUE_NAME}
      - INDEXING_DRIVE_SERVICE_ROUTING_KEY=${INDEXING_DRIVE_SERVICE_ROUTING_KEY}
      - INDEXING_ERROR_QUEUE_NAME=${INDEXING_ERROR_QUEUE_NAME}
      - INDEXING_ERROR_ROUTING_KEY=${INDEXING_ERROR_ROUTING_KEY}
      - INDEXING_ELASTIC_URLS=${INDEXING_ELASTIC_URLS}
    depends_on:
      - rabbitmq

  elasticService:
    image: elastic-spring-boot
    build: ./elastic-service
    environment:
      - INDEXING_ELASTIC_SERVICE_HC_PORT=${INDEXING_ELASTIC_SERVICE_HC_PORT}
      - INDEXING_RABBIT_URL=${INDEXING_RABBIT_URL}
      - INDEXING_EXCHANGE_NAME=${INDEXING_EXCHANGE_NAME}
      - INDEXING_ELASTIC_SERVICE_QUEUE_NAME=${INDEXING_ELASTIC_SERVICE_QUEUE_NAME}
      - INDEXING_ELASTIC_SERVICE_ROUTING_KEY=${INDEXING_ELASTIC_SERVICE_ROUTING_KEY}
      - INDEXING_ERROR_QUEUE_NAME=${INDEXING_ERROR_QUEUE_NAME}
      - INDEXING_ERROR_ROUTING_KEY=${INDEXING_ERROR_ROUTING_KEY}
      - INDEXING_ELASTIC_URLS=${INDEXING_ELASTIC_URLS}
    depends_on:
      - rabbitmq

  parsingService:
    image: parsing-spring-boot
    build: ./parsing-service
    environment:
      - INDEXING_PARSING_SERVICE_HC_PORT=${INDEXING_PARSING_SERVICE_HC_PORT}
      - INDEXING_RABBIT_URL=${INDEXING_RABBIT_URL}
      - INDEXING_EXCHANGE_NAME=${INDEXING_EXCHANGE_NAME}
      - INDEXING_PARSING_SERVICE_QUEUE_NAME=${INDEXING_PARSING_SERVICE_QUEUE_NAME}
      - INDEXING_PARSING_SERVICE_ROUTING_KEY=${INDEXING_PARSING_SERVICE_ROUTING_KEY}
      - INDEXING_ELASTIC_SERVICE_QUEUE_NAME=${INDEXING_ELASTIC_SERVICE_QUEUE_NAME}
      - INDEXING_ELASTIC_SERVICE_ROUTING_KEY=${INDEXING_ELASTIC_SERVICE_ROUTING_KEY}
      - INDEXING_ERROR_QUEUE_NAME=${INDEXING_ERROR_QUEUE_NAME}
      - INDEXING_ERROR_ROUTING_KEY=${INDEXING_ERROR_ROUTING_KEY}
      - INDEXING_CHUNK_SIZE=${INDEXING_CHUNK_SIZE}
      - INDEXING_SUFF_PRE_SIZE=${INDEXING_SUFF_PRE_SIZE}
      - INDEXING_FOLDER_TYPE=${INDEXING_FOLDER_TYPE}
      - INDEXING_FILE_SERVICE_URL=${INDEXING_FILE_SERVICE_URL}
      - INDEXING_DOWNLOAD_SERVICE_URL=${INDEXING_DOWNLOAD_SERVICE_URL}
    depends_on:
      - rabbitmq

  search:
    build: ./search-service
    environment:
      - INDEXING_SEARCH_URL=${INDEXING_SEARCH_URL}
      - INDEXING_OLDEST_YEAR=${INDEXING_OLDEST_YEAR}
      - INDEXING_OLDEST_MONTH=${INDEXING_OLDEST_MONTH}
      - INDEXING_OLDEST_DAY=${INDEXING_OLDEST_DAY}
      - INDEXING_FOLDER_TYPE=${INDEXING_FOLDER_TYPE}
      - INDEXING_FILE_SERVICE_URL=${INDEXING_FILE_SERVICE_URL}
      - INDEXING_PERMISSION_SERVICE_URL=${INDEXING_PERMISSION_SERVICE_URL}
      - INDEXING_ELASTIC_URLS=${INDEXING_ELASTIC_URLS}
    ports:
      - 8005:8005
    restart: on-failure

 errorService:
   image: error-spring-boot
   build: ./error-service
   environment:
     - INDEXING_ERROR_SERVICE_START_TIME=${INDEXING_ERROR_SERVICE_START_TIME}
     - INDEXING_ERROR_SERVICE_END_TIME=${INDEXING_ERROR_SERVICE_END_TIME}
     - INDEXING_RABBIT_URL=${INDEXING_RABBIT_URL}
     - INDEXING_EXCHANGE_NAME=${INDEXING_EXCHANGE_NAME}
     - INDEXING_EVENTS_QUEUE_NAME=${INDEXING_EVENTS_QUEUE_NAME}
     - INDEXING_EVENTS_ROUTING_KEY=${INDEXING_EVENTS_ROUTING_KEY}
     - INDEXING_ERROR_QUEUE_NAME=${INDEXING_ERROR_QUEUE_NAME}
     - INDEXING_ERROR_ROUTING_KEY=${INDEXING_ERROR_ROUTING_KEY}
     - INDEXING_ERROR_SERVICE_HC_PORT=${INDEXING_ERROR_SERVICE_HC_PORT}
   depends_on:
     - rabbitmq