version: "2.1"
services:
  # rabbitmq:
  #   image: 'drivehub.azurecr.io/meateam/rabbitmq:latest'
  #   hostname: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://rabbitmq:15672" ]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 15

  managerService:
    image: manager-spring-boot
    build: ./manager-service
    environment:
      - INDEXING_RABBIT_URL=${INDEXING_RABBIT_URL}
      - INDEXING_EXCHANGE_NAME=${INDEXING_EXCHANGE_NAME}
      - INDEXING_EVENTS_QUEUE_NAME=${INDEXING_EVENTS_QUEUE_NAME}
      - INDEXING_EVENTS_ROUTING_KEY=${INDEXING_EVENTS_ROUTING_KEY}
      - INDEXING_DELETE_QUEUE_NAME=${INDEXING_DELETE_QUEUE_NAME}
      - INDEXING_DELETE_ROUTING_KEY=${INDEXING_DELETE_ROUTING_KEY}
      - INDEXING_DRIVE_SERVICE_QUEUE_NAME=${INDEXING_DRIVE_SERVICE_QUEUE_NAME}
      - INDEXING_DRIVE_SERVICE_ROUTING_KEY=${INDEXING_DRIVE_SERVICE_ROUTING_KEY}
      - INDEXING_ERROR_QUEUE_NAME=${INDEXING_ERROR_QUEUE_NAME}
      - INDEXING_ERROR_ROUTING_KEY=${INDEXING_ERROR_ROUTING_KEY}
#    volumes:
#       - ${INDEXING_MAVEN_SETTINGS_FOLDER}:/root/.m2   # comment this line if you do not want to use you local maven settings or if you do not have a local maven installed
    # depends_on:
    #   - rabbitmq

  driveService:
    image: drive-spring-boot
    build: ./drive-service
    environment:
      - INDEXING_RABBIT_URL=${INDEXING_RABBIT_URL}
      - INDEXING_EXCHANGE_NAME=${INDEXING_EXCHANGE_NAME}
      - INDEXING_EVENTS_QUEUE_NAME=${INDEXING_EVENTS_QUEUE_NAME}
      - INDEXING_EVENTS_ROUTING_KEY=${INDEXING_EVENTS_ROUTING_KEY}
      - INDEXING_DELETE_QUEUE_NAME=${INDEXING_DELETE_QUEUE_NAME}
      - INDEXING_DELETE_ROUTING_KEY=${INDEXING_DELETE_ROUTING_KEY}
      - INDEXING_DRIVE_SERVICE_QUEUE_NAME=${INDEXING_DRIVE_SERVICE_QUEUE_NAME}
      - INDEXING_DRIVE_SERVICE_ROUTING_KEY=${INDEXING_DRIVE_SERVICE_ROUTING_KEY}
      - INDEXING_ERROR_QUEUE_NAME=${INDEXING_ERROR_QUEUE_NAME}
      - INDEXING_ERROR_ROUTING_KEY=${INDEXING_ERROR_ROUTING_KEY}
      - INDEXING_PARSING_SERVICE_QUEUE_NAME=${INDEXING_PARSING_SERVICE_QUEUE_NAME}
      - INDEXING_PARSING_SERVICE_ROUTING_KEY=${INDEXING_PARSING_SERVICE_ROUTING_KEY}
      - INDEXING_ELASTIC_SERVICE_QUEUE_NAME=${INDEXING_ELASTIC_SERVICE_QUEUE_NAME}
      - INDEXING_ELASTIC_SERVICE_ROUTING_KEY=${INDEXING_ELASTIC_SERVICE_ROUTING_KEY}
      # - INDEXING_DRIVE_URL=${INDEXING_DRIVE_URL}
      # - INDEXING_DOWNLOAD_SERVICE_PORT=${INDEXING_DOWNLOAD_SERVICE_PORT}
      # - INDEXING_FILE_SERVICE_PORT=${INDEXING_FILE_SERVICE_PORT}
      # - INDEXING_USER_SERVICE_PORT=${INDEXING_USER_SERVICE_PORT}
      # - INDEXING_PERMISSION_SERVICE_PORT=${INDEXING_PERMISSION_SERVICE_PORT}
      - INDEXING_FOLDER_TYPE=${INDEXING_FOLDER_TYPE}
      - INDEXING_FILE_SERVICE_URL=${INDEXING_FILE_SERVICE_URL}
      - INDEXING_PERMISSION_SERVICE_URL=${INDEXING_PERMISSION_SERVICE_URL}
      - INDEXING_USER_SERVICE_URL=${INDEXING_USER_SERVICE_URL}
      - INDEXING_DOWNLOAD_SERVICE_URL=${INDEXING_DOWNLOAD_SERVICE_URL}
#    volumes:
#       - ${INDEXING_MAVEN_SETTINGS_FOLDER}:/root/.m2   # comment this line if you do not want to use you local maven settings or if you do not have a local maven installed
    # depends_on:
    #   - rabbitmq

  deleteService:
    image: delete-spring-boot
    build: ./delete-service
    environment:
      - INDEXING_RABBIT_URL=${INDEXING_RABBIT_URL}
      - INDEXING_EXCHANGE_NAME=${INDEXING_EXCHANGE_NAME}
      - INDEXING_EVENTS_QUEUE_NAME=${INDEXING_EVENTS_QUEUE_NAME}
      - INDEXING_EVENTS_ROUTING_KEY=${INDEXING_EVENTS_ROUTING_KEY}
      - INDEXING_DELETE_QUEUE_NAME=${INDEXING_DELETE_QUEUE_NAME}
      - INDEXING_DELETE_ROUTING_KEY=${INDEXING_DELETE_ROUTING_KEY}
      - INDEXING_DRIVE_SERVICE_QUEUE_NAME=${INDEXING_DRIVE_SERVICE_QUEUE_NAME}
      - INDEXING_DRIVE_SERVICE_ROUTING_KEY=${INDEXING_DRIVE_SERVICE_ROUTING_KEY}
      - INDEXING_ERROR_QUEUE_NAME=${INDEXING_ERROR_QUEUE_NAME}
      - INDEXING_ERROR_ROUTING_KEY=${INDEXING_ERROR_ROUTING_KEY}
      - INDEXING_ELASTIC_URLS=${INDEXING_ELASTIC_URLS}
      # - INDEXING_ELASTIC_HOST=${INDEXING_ELASTIC_HOST}
      # - INDEXING_ELASTIC_PORT=${INDEXING_ELASTIC_PORT}
      # - INDEXING_ELASTIC_PROTOCOL=${INDEXING_ELASTIC_PROTOCOL}
#    volumes:
#       - ${INDEXING_MAVEN_SETTINGS_FOLDER}:/root/.m2   # comment this line if you do not want to use you local maven settings or if you do not have a local maven installed
    # depends_on:
    #   - rabbitmq

  elasticService:
    image: elastic-spring-boot
    build: ./elastic-service
    environment:
      - INDEXING_RABBIT_URL=${INDEXING_RABBIT_URL}
      - INDEXING_EXCHANGE_NAME=${INDEXING_EXCHANGE_NAME}
      - INDEXING_ELASTIC_SERVICE_QUEUE_NAME=${INDEXING_ELASTIC_SERVICE_QUEUE_NAME}
      - INDEXING_ELASTIC_SERVICE_ROUTING_KEY=${INDEXING_ELASTIC_SERVICE_ROUTING_KEY}
      - INDEXING_ERROR_QUEUE_NAME=${INDEXING_ERROR_QUEUE_NAME}
      - INDEXING_ERROR_ROUTING_KEY=${INDEXING_ERROR_ROUTING_KEY}
      - INDEXING_ELASTIC_HOST=${INDEXING_ELASTIC_HOST}
      - INDEXING_ELASTIC_PORT=${INDEXING_ELASTIC_PORT}
      - INDEXING_ELASTIC_PROTOCOL=${INDEXING_ELASTIC_PROTOCOL}
      - INDEXING_ELASTIC_URLS=${INDEXING_ELASTIC_URLS}
#    volumes:
#       - ${INDEXING_MAVEN_SETTINGS_FOLDER}:/root/.m2   # comment this line if you do not want to use you local maven settings or if you do not have a local maven installed
    # depends_on:
    #   - rabbitmq

#  errorService:
#    image: error-spring-boot
#    build: ./error-service
#    environment:
#      - INDEXING_RABBIT_URL=${INDEXING_RABBIT_URL}
#      - INDEXING_EXCHANGE_NAME=${INDEXING_EXCHANGE_NAME}
#      - INDEXING_DELETE_QUEUE_NAME=${INDEXING_DELETE_QUEUE_NAME}
#      - INDEXING_DELETE_ROUTING_KEY=${INDEXING_DELETE_ROUTING_KEY}
#      - INDEXING_ERROR_QUEUE_NAME=${INDEXING_ERROR_QUEUE_NAME}
#      - INDEXING_ERROR_ROUTING_KEY=${INDEXING_ERROR_ROUTING_KEY}
#      - INDEXING_DRIVE_URL=${INDEXING_DRIVE_URL}
#      - INDEXING_DOWNLOAD_SERVICE_PORT=${INDEXING_DOWNLOAD_SERVICE_PORT}
#      - INDEXING_DOWNLOAD_FOLDER_PATH=${INDEXING_DOWNLOAD_FOLDER_PATH}
#      - INDEXING_CHUNK_SIZE=${INDEXING_CHUNK_SIZE}
#      - INDEXING_PRE_SUFF_SIZE=${INDEXING_PRE_SUFF_SIZE}
#
#    volumes:
#      - ${INDEXING_MAVEN_SETTINGS_FOLDER}:/root/.m2   # comment this line if you do not want to use you local maven settings or if you do not have a local maven installed
#    depends_on:
#      - rabbitmq


  parsingService:
    image: parsing-spring-boot
    build: ./parsing-service
    environment:
      - INDEXING_RABBIT_URL=${INDEXING_RABBIT_URL}
      - INDEXING_EXCHANGE_NAME=${INDEXING_EXCHANGE_NAME}
      - INDEXING_PARSING_SERVICE_QUEUE_NAME=${INDEXING_PARSING_SERVICE_QUEUE_NAME}
      - INDEXING_PARSING_SERVICE_ROUTING_KEY=${INDEXING_PARSING_SERVICE_ROUTING_KEY}
      - INDEXING_ELASTIC_SERVICE_QUEUE_NAME=${INDEXING_ELASTIC_SERVICE_QUEUE_NAME}
      - INDEXING_ELASTIC_SERVICE_ROUTING_KEY=${INDEXING_ELASTIC_SERVICE_ROUTING_KEY}
      - INDEXING_ERROR_QUEUE_NAME=${INDEXING_ERROR_QUEUE_NAME}
      - INDEXING_ERROR_ROUTING_KEY=${INDEXING_ERROR_ROUTING_KEY}
      # - INDEXING_DRIVE_URL=${INDEXING_DRIVE_URL}
      # - INDEXING_DOWNLOAD_SERVICE_PORT=${INDEXING_DOWNLOAD_SERVICE_PORT}
      # - INDEXING_FILE_SERVICE_PORT=${INDEXING_FILE_SERVICE_PORT}
      # - INDEXING_USER_SERVICE_PORT=${INDEXING_USER_SERVICE_PORT}
      - INDEXING_CHUNK_SIZE=${INDEXING_CHUNK_SIZE}
      - INDEXING_SUFF_PRE_SIZE=${INDEXING_SUFF_PRE_SIZE}
      - INDEXING_FOLDER_TYPE=${INDEXING_FOLDER_TYPE}
      - INDEXING_FILE_SERVICE_URL=${INDEXING_FILE_SERVICE_URL}
      - INDEXING_PERMISSION_SERVICE_URL=${INDEXING_PERMISSION_SERVICE_URL}
      - INDEXING_USER_SERVICE_URL=${INDEXING_USER_SERVICE_URL}
      - INDEXING_DOWNLOAD_SERVICE_URL=${INDEXING_DOWNLOAD_SERVICE_URL}
#    volumes:
      # - ${INDEXING_MAVEN_SETTINGS_FOLDER}:/root/.m2   # comment this line if you do not want to use you local maven settings or if you do not have a local maven installed
    # depends_on:
    #   - rabbitmq

  search:
    build: ./search-service
    environment:
      - INDEXING_DRIVE_URL=${INDEXING_DRIVE_URL}
      - INDEXING_FILE_SERVICE_PORT=${INDEXING_FILE_SERVICE_PORT}
      - INDEXING_PERMISSION_SERVICE_PORT=${INDEXING_PERMISSION_SERVICE_PORT}
      # - INDEXING_ELASTIC_HOST=${INDEXING_ELASTIC_HOST}
      # - INDEXING_ELASTIC_PORT=${INDEXING_ELASTIC_PORT}
      # - INDEXING_ELASTIC_PROTOCOL=${INDEXING_ELASTIC_PROTOCOL}
      - INDEXING_SEARCH_URL=${INDEXING_SEARCH_URL}
      - INDEXING_OLDEST_YEAR=${INDEXING_OLDEST_YEAR}
      - INDEXING_OLDEST_MONTH=${INDEXING_OLDEST_MONTH}
      - INDEXING_OLDEST_DAY=${INDEXING_OLDEST_DAY}
      - INDEXING_FOLDER_TYPE=${INDEXING_FOLDER_TYPE}
      - INDEXING_FILE_SERVICE_URL=${INDEXING_FILE_SERVICE_URL}
      - INDEXING_PERMISSION_SERVICE_URL=${INDEXING_PERMISSION_SERVICE_URL}
      - INDEXING_USER_SERVICE_URL=${INDEXING_USER_SERVICE_URL}
      - INDEXING_DOWNLOAD_SERVICE_URL=${INDEXING_DOWNLOAD_SERVICE_URL}
      - INDEXING_ELASTIC_URLS=${INDEXING_ELASTIC_URLS}
    ports:
      - 8005:8005
    restart: on-failure